**Importando a api NumPy**

In [0]:
import numpy as np

**Criando arrays**

In [0]:
n = np.array([1,2,3])

In [5]:
n[0]

1

**Cria array como o range do python, um range de números de acordo o parâmetro**

In [9]:
n = np.arange(20);
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
#quantidade dos elementos
n.size

20

In [12]:
n = np.array([[1,2,3], [4,5,6]])

n.size

6

In [14]:
n = np.arange(5,20)
n

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
n = np.arange(1, 20, 2)
n

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [19]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

a1 + a2

array([5, 7, 9])

In [22]:
a1 = np.array([[1,2,3], [1,5,6] ])
a2 = np.array([[4,5,6], [1,1,1]])

a1 + a2

array([[5, 7, 9],
       [2, 6, 7]])