In [0]:
import numpy as np

In [6]:
a = np.array([5,6,9])
a.ndim

1

In [3]:
a[0]

5

In [5]:
a = np.array([[1,2], [3,4], [3, 5] ])
a.ndim

2

In [7]:
#tamanho elementos na base (float64, float32...)
a.itemsize

8

In [8]:
a.dtype

dtype('int64')

In [9]:
a = np.array([[1,2], [3,4], [3, 5] ], dtype=np.float64)
a.dtype

dtype('float64')

In [11]:
a.itemsize

8

In [12]:
#qtd elementos
a.size

6

In [13]:
a.shape

(3, 2)

In [14]:
a = np.array([[1,2], [3,4], [3, 5] ], dtype=np.complex)
a


array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [3.+0.j, 5.+0.j]])

**Cria array com zeros**

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**Cria array com 1s**

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.arange(1,5)


array([1, 2, 3, 4])

In [22]:
np.arange(1, 5, 5)

array([1])

In [23]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [24]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [25]:
a = np.array([ [1,2], [3,4], [5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
a.shape

(3, 2)

In [27]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
a.reshape(6, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [32]:
#retorna elementos em linha

a.ravel()

array([1, 2, 3, 4, 5, 6])

In [31]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
a.min()

1

In [34]:
a.max()

6

In [0]:
a.sum()

In [35]:
#Colunas de sima para baixo
a.sum(axis=0)

array([ 9, 12])

In [36]:
#linhas da esquerda para direita
a.sum(axis=1)

array([ 3,  7, 11])

In [37]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [39]:
#Desvio padrão
np.std(a)

1.707825127659933

In [43]:
a = np.array([[1,2], [3,4] ])
a

array([[1, 2],
       [3, 4]])

In [44]:
b = np.array([[5,6], [7,8] ])
b

array([[5, 6],
       [7, 8]])

In [45]:
a + b

array([[ 6,  8],
       [10, 12]])

In [46]:
a.dot(b)

array([[19, 22],
       [43, 50]])