In [0]:
import numpy as np

In [2]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
for row in a:
  print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [4]:
for row in a:
  for cell in row:
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [5]:
for cell in a.flatten():
  print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [6]:
for x in np.nditer(a,order='C'):
  print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [8]:
for x in np.nditer(a, order='F', flags=['external_loop']):
  print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [11]:
for x in np.nditer(a, op_flags=['readwrite']):
  x[...] = x * x

a

array([[        0,         1,       256,      6561],
       [    65536,    390625,   1679616,   5764801],
       [ 16777216,  43046721, 100000000, 214358881]])

In [12]:
b = np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [13]:
for x,y in np.nditer([a,b]):
  print(x,y)

0 3
1 3
256 3
6561 3
65536 7
390625 7
1679616 7
5764801 7
16777216 11
43046721 11
100000000 11
214358881 11
